### PR TITLE
update readme for Fix the token verify error 

### LINKED ISSUE #68: Inconsistent description between the README file and the implement
Please see the following links:

* https://github.com/kubesphere-sigs/ks-devops/pull/56#discussion_r674057827
* https://github.com/kubesphere-sigs/ks-devops#apis

/good-first-issue

### PR DESCRIPTION
**Pull request by AbdelouahabMbarki**
Fix #68
description : update description in the README file for the the implement #56

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
Thanks for your quick action. That's wonderful.
/lgtm

**Comment by JohnNiang** [comment]
/lgtm

BTW, I've already updated <https://www.postman.com/ks-devops/workspace/kubesphere-devops>.

**Comment by LinuxSuRen** [comment]
> /lgtm
> 
> BTW, I've already updated https://www.postman.com/ks-devops/workspace/kubesphere-devops.

That's great!!!

**Pull request merged**
